name: auto_titanic
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.0
  dropdown_button2: ^2.3.9
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_html_v3: ^3.0.6
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  internet_connection_checker_plus: ^2.1.0
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  permission_handler: ^11.1.0
  quill_html_editor: ^2.2.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/svg/
    - assets/images/
    - assets/images/brands/
    - assets/images/dealers/
