name: auto_titanic
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.0
  flutter:
    sdk: flutter
  flutter_html_v3: ^3.0.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  internet_connection_checker_plus: ^2.1.0
  package_info_plus: ^4.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/svg/
    - assets/images/
